### ISSUE TITLE
inline SVG file corupted

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [paralect/ship#28]
![image](https://user-images.githubusercontent.com/20900930/36935851-fddc0d34-1f0d-11e8-94ad-ca7627628916.png)

Instagram icon corrupted - looks like collision with other svg files

Correct Instagram icon - 
![image](https://user-images.githubusercontent.com/20900930/36935880-540a6070-1f0e-11e8-8790-8fc90ea14a37.png)

**Comment by ezhivitsa** [comment]
@AliaksandrHudnyi How to replicate this issue? I think that problem here that you incorrectly inserted svg file. The svg icons on the following images are identical, but due to optical illusion, it seems that they differ.

![screenshot_4](https://user-images.githubusercontent.com/6461311/38172586-904781b6-35b7-11e8-9f04-46e25b8bc8b1.png)
![screenshot_3](https://user-images.githubusercontent.com/6461311/38172587-906d40c2-35b7-11e8-844c-652949c4a046.png)

**Comment by AliaksandrHudnyi** [comment]
To reproduce this issue:
1) Import 2+ new svg files
2) Svg files should be more complex, try for e.g this svg's
[business_card_no_6.zip](https://github.com/paralect/ship/files/1868276/business_card_no_6.zip)

Thanks

**Comment by ezhivitsa** [comment]
@AliaksandrHudnyi Please, test

**Comment by AliaksandrHudnyi** [comment]
Tested. Fixed. @ezhivitsa
