### ISSUE TITLE
Are there any plans to shift from pages router to app router?

### ISSUE THREAD

**Issue by shivam-jainn** [paralect/ship#327]

**Comment by fruneen** [comment]
Hi there!
Yes, we have this task in backlog: https://github.com/orgs/paralect/projects/1/views/1?pane=issue&itemId=39913952
But the problem in our stack, like a TanStack Query, which works in more difficult way (more abstraction layers, which implement the same logic in pages router)

But the problem is in our tech stack, for example, in the TanStack Query, which works in a more complex way with app router (more abstraction layers that implement the same logic as in pages router).

That's only 1 case, but I'm planning to add a detailed description in the task in github projects
